name: Format
on:
    pull_request:

permissions:
    repository-projects: read

jobs:
    cmake:
        name: CMake
        runs-on: ubuntu-latest
        steps:
            - name: Install cmake-format
              run: python3 -m pip install cmake-format==0.6.13
            - name: Checkout pizmidi
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Check formatting
              run: ./.github/scripts/checkfmt-cmake.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

    cpp:
        name: C/C++
        runs-on: ubuntu-latest
        steps:
            - name: Checkout pizmidi
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Install clang-format
              run: sudo ./.github/scripts/install-clang-format.sh 14
            - name: Check formatting
              run: ./.github/scripts/checkfmt-cpp.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
